/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_szxb_jni_sendCmd */

#ifndef _Included_com_szxb_jni_sendCmd
#define _Included_com_szxb_jni_sendCmd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_szxb_jni_sendCmd
 * Method:    getCardInfo
 * Signature: ([BI[B)I
 */
JNIEXPORT jint JNICALL Java_com_szxb_jni_sendCmd_getCardInfo
  (JNIEnv *, jobject, jbyteArray, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
